name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/main.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      ## Test
      - name: Run component + unit tests
        run: pnpm test:ci

      # - name: Run e2e tests
      #   run: |
      #     yarn test:ci-e2e
      #     yarn coverage
